export const initialState = {
  user : null,
  allUsers : null,
  allSongs : null,
  allArtists : null,
  allAlbums : null,
  artistFilter : null,
  albumFilter : null,
  languageFilter : null,
  alertType : null,
  isSongPlaying : false,
  songIndex : 0,
  filterTerm : "all",
  searchTerm: "",
};
